favouriteQ/favouriteQ/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'questions.views.current_question'),
    url(r'^ajax_suggest$', 'questions.views.ajax_suggest'),
    url(r'^archive$', 'questions.views.archive'),
    url(r'^archive/(?P<slug>[-\w]+)$', 'questions.views.detail'),
)

favouriteQ/questions/models.py
from django.db import models
from django.template.defaultfilters import slugify
from lazy import lazy


class QuestionManager(models.Manager):
    def get_current_question(self):
        """
        Get the question with the most recent asked date
        (null asked date means question hasn't been asked)
        """
        return self.order_by('-asked_date').filter(asked_date__isnull=False,
                                                   approved=1)[0]

    def get_new_question(self, exclude=None):
        # get priority questions first
        questions = self.order_by('?').filter(asked_date__isnull=True,
                                              priority=1,
                                              approved=1).exclude(id=exclude)

        # no priority questions then get from non-priority
        if not questions:
            questions = self.order_by('?').filter(asked_date__isnull=True,
                                                  priority=0,
                                                  approved=1)
        #TODO: add check and behaviour if we don't have a question.
        return questions[0]

    def get_num_unasked_questions(self):
        return self.filter(asked_date__isnull=True, approved=1).count()


class Question(models.Model):
    question = models.CharField(max_length=140)
    slug = models.CharField(max_length=140, null=True)
    # Null if question hasn't been asked
    asked_date = models.DateTimeField(null=True, blank=True)
    # deafult to not priority
    priority = models.BooleanField()
    approved = models.BooleanField()
    # Twitter user which suggested the question
    # TODO: update this to link to be an foreign key to Person
    twitter_user = models.CharField(max_length=140, null=True, blank=True)

    # System fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = QuestionManager()

    def __unicode__(self):
        return self.question

    @lazy
    def num(self):
        count = Question.objects.filter(asked_date__lte=self.asked_date).count()
        return count

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.question)
        super(Question, self).save(*args, **kwargs)


class Person(models.Model):
    twitter_username = models.CharField(max_length=20)
    first_name = models.CharField(max_length=25)
    surname = models.CharField(max_length=25)
    middle_names = models.CharField(max_length=25, blank=True)
    # automatic system fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.twitter_username

    @property
    def name(self):
        if self.middle_names and self.surname:
            return '%s %s %s' % (self.first_name, self.middle_names, self.surname)
        elif self.surname:
            return '%s %s' % (self.first_name, self.surname)
        else:
            # Person should always have firstname set as a minimum
            return self.first_name

    class Meta:
        verbose_name_plural = "People"


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)  # Increased due to strange tweets with more than 140 characters
    person = models.ForeignKey(Person)
    tweet_id = models.CharField(max_length=50)

    # automatic system fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.answer_text

favouriteQ/questions/forms.py
from django import forms


class QuestionForm(forms.Form):
    question = forms.CharField(widget=forms.Textarea(attrs={'rows': '5',
                                                            'cols': '5',
                                                            'placeholder': 'What\'s your favourite...',
                                                            'maxlength': '140',
                                                            'required': 'required'
                                                    }), max_length=140, required=True, label='What\'s your favourite...')

    twitter_user = forms.CharField(widget=forms.Textarea(attrs={'rows': '1',
                                                                'cols': '25',
                                                                'placeholder': '@your_twitter_handle (optional)',
                                                                'maxlength': '20',
                                                    }), max_length=20, required=False, label='@your_twitter_handle (optional)')

favouriteQ/questions/views.py
from django.conf import settings
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from forms import QuestionForm
from questions.models import Question


def current_question(request):
    question = Question.objects.get_current_question()
    params = {"question": question, "current": True}
    return render_template(request, "questions/current_question.html", params)


def archive(request):
    questions = Question.objects.order_by('-asked_date').filter(asked_date__isnull=False)
    params = {"questions": questions}
    return render_template(request, "questions/archive.html", params)


def detail(request, slug):
    question = get_object_or_404(Question,
                                 Q(asked_date__isnull=False, slug=slug))

    params = {"question": question}
    return render_template(request, "questions/current_question.html", params)


def ajax_suggest(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            q = Question(question=form.cleaned_data['question'],
                         twitter_user=form.cleaned_data['twitter_user'],
                         approved=False)
            q.save()
            message = "success"
        else:
            # shouldn't be reached accept if HTML5 validation is bypassed
            message = "form not valid"
    else:
        message = "you must post"
    return HttpResponse(message)


# def handle_form(request):
#     if request.method == 'POST':
#         form = QuestionForm(request.POST)
#         if form.is_valid():
#             q = Question(question=form.cleaned_data['question'],
#                          approved=False)
#             q.save()
#             print "success"
#         else:
#             # shouldn't be reached accept if HTML5 validation is bypassed
#             print "form not valid"
#     else:
#         form = QuestionForm()
#     return form


def render_template(request, template, params):
    params['twitter_account'] = settings.TWITTER_USER
    # Deal with Form submission which is on everypage
    #params['form'] = handle_form(request)
    params['form'] = QuestionForm()
    return render_to_response(template, params,
                              context_instance=RequestContext(request))

favouriteQ/questions/templates/questions/archive.html
{% extends 'questions/layout.html' %}

{% block content %}

  <div class="question">

    <div id="questionbox">
      <h2 class="question_title">Question Archive</h2>
      <div class="divider"></div>
      <ul class="question_answers">
        {% for question in questions %}
        <li>
          <div class="question_answer">
            <p class="answer"><a href="{% url questions.views.detail question.slug %}">#{{ question.num }} {{ question.question }}</a></p>
            <p class="author">
              {{ question.asked_date|date:"jS \o\f F o" }}
              <br/>
              {{ question.answer_set.count }} answers
            </p>
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>

{% endblock %}

favouriteQ/questions/templates/questions/current_question.html
{% extends 'questions/layout.html' %}

{% block content %}

  <div class="question">

    <div id="questionbox">
      <h2 class="question_title"><span>#{{ question.num }}</span> {{ question.question }}</h2>
      {% if current %}
      <div class="tweet">
        <span>Tweet your answer: </span>
        <a href="https://twitter.com/intent/tweet?screen_name={{ twitter_account }}" class="twitter-mention-button" data-related="guntlondon" data-dnt="true">Tweet to {{ twitter_account }}</a>
      </div>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      {% else %}
      <div class="divider"></div>
      {% endif %}
    </div>
    <ul class="question_answers">
      {% for answer in question.answer_set.all %}
      <li>
        <div class="question_answer">
          <p class="answer">{{ answer.answer_text }}</p>
          <p class="author">{{ answer.person.name }} <a href="http://www.twitter.com/{{ answer.person }}" rel="external">@{{ answer.person }}</a> / {{answer.created_at|date:"g:ia"}}</p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

favouriteQ/questions/templates/questions/layout.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <!--[if lt IE 9]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
    <title>Your Favourite Question</title>
    <meta name="description" content="What's your favourite question? Aggregating all answers to the daily questions posted by @favouriteq on twitter">

    <meta name="viewport" content="width=device-width">
    <link href='http://fonts.googleapis.com/css?family=Josefin+Slab:700,700italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{{STATIC_URL}}questions/css/style.css">
    <link rel="shortcut icon" href="{{STATIC_URL}}questions/img/favicon.ico">

    <script src="{{STATIC_URL}}questions/js/libs/modernizr-2.5.3.min.js"></script>
</head>
<body>

    <header>

        <nav>
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="#about" class="collapsable-trigger">About</a></li>
                <li><a href="#suggest" class="collapsable-trigger">Suggest</a></li>
                <li><a href="{% url questions.views.archive %}">Archive</a></li>
                <li class="last"><a href="http://twitter.com/{{ twitter_account }}" rel="external">@{{ twitter_account }}</a></li>
            </ul>
        </nav>

        <h1 id="logo"><span>Q:</span></h1>

    </header>

    <div role="main" id="main">

        <div id="about" class="collapsable">
            <div class="collapsable-clip">
                <h2>What is it all about?</h2>
                <h3><span>Isn’t there a question you’ve always wanted to ask?</span></h3>
                <p>This is the place to come to ask and answer those questions.</p>
                <p>From favourite unit of measurement to file format, we ask all those burning questions.</p>
                <p>Everyday we will be posting a new question out to you.</p>
                <p>You can reply to these via the best of all the social media networks, Twitter.</p>
            </div>
        </div>

        <div id="suggest" class="collapsable">
            <div class="collapsable-clip">
                <h2>What is the question you always wanted to ask?</h2>
                <p>If you have a burning question to ask everyone, please send it to us using the form below. </p>
                <form action="/" method="post" id="suggest-form">
                    {% csrf_token %}
                    <fieldset>
                        <legend>Enter your question</legend>

                        <div class="input-container">
                            {{ form.question }}
                            <label for="id_question"></label>
                        </div>

                        <div class="input-container">
                            {{ form.twitter_user }}
                        </div>

                        <input type="submit" value="Submit" />

                        <div id="status">
                            <img src="/static/questions/img/loading.gif" alt="loading">
                            <p>...</p>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>


        {% block content %}
        {% endblock %}


        <footer>

        </footer>

    </div>

    <script src="http://guntlondon.github.io/gunt-badge/gunt-badge.min.js"></script>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{STATIC_URL}}questions/js/libs/jquery-1.7.1.min.js"><\/script>')</script>

    <script src="{{STATIC_URL}}questions/js/plugins.js"></script>
    <script src="{{STATIC_URL}}questions/js/script.js"></script>

    <script>
        var _gaq=[['_setAccount','UA-29684348-3'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
</body>
</html>